<?php

declare(strict_types=1);

namespace Components\Tests;

use Components\Hotfire\ComponentGenerator;
use InvalidArgumentException;
use PHPUnit\Framework\TestCase;

final class HotfireGeneratorTest extends TestCase
{
    public function testDottedAndSlashedNamesResolveToSamePaths(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');

        self::assertSame(
            $generator->viewRelative('post.create'),
            $generator->viewRelative('post/create'),
        );
        self::assertSame('components/hotfire/post/🔥create/create.view', $generator->viewRelative('post.create'));
    }

    public function testExpectedClassAndNamespace(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');

        self::assertSame('components/hotfire/post/🔥create/create.view', $generator->viewRelative('post.create'));
        self::assertSame('Create', $generator->className('post.create'));
        self::assertSame('App\\Components\\Post', $generator->classNamespace('post.create'));
        self::assertSame('App\\Components', $generator->classNamespace('post'));
        self::assertSame('CreateForm', $generator->className('post.create-form'));
    }

    public function testCamelCaseSingleComponentGetsKebabFolderWithEmoji(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');

        self::assertSame('BottomLogout', $generator->className('BottomLogout'));
        self::assertSame('App\\Components', $generator->classNamespace('BottomLogout'));
        self::assertSame('components/hotfire/🔥bottom-logout/bottom-logout.view', $generator->viewRelative('BottomLogout'));
        self::assertSame('/views/components/hotfire/🔥bottom-logout/bottom-logout.php', $generator->classPath('BottomLogout'));
    }

    public function testEmojiIsConfigurable(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components', '', '⚡');

        self::assertSame('components/hotfire/post/⚡create/create.view', $generator->viewRelative('post.create'));
    }

    public function testViewPathSitsUnderHotfirePrefix(): void
    {
        $generator = new ComponentGenerator('/project/views', 'App\\Components');

        self::assertSame(
            '/project/views/components/hotfire/post/🔥create/create.view.php',
            $generator->viewPath('post.create'),
        );
        self::assertSame(
            '/project/views/components/hotfire/post/🔥create/create.js',
            $generator->sidecarPath('post.create', 'js'),
        );
        self::assertSame(
            '/project/views/components/hotfire/post/🔥create/create.global.css',
            $generator->sidecarPath('post.create', 'global.css'),
        );
    }

    public function testGeneratedClassDeclaresExplicitViewAndProps(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');
        $class = $generator->classContent('post.create', ['title', 'content']);

        self::assertStringContainsString('namespace App\\Components\\Post;', $class);
        self::assertStringContainsString('final class Create extends Component', $class);
        self::assertStringContainsString("protected string \$view = 'components/hotfire/post/🔥create/create.view';", $class);
        self::assertStringContainsString('public string $title = \'\';', $class);
        self::assertStringContainsString('public string $content = \'\';', $class);
        self::assertStringContainsString('public function save(): void', $class);
    }

    public function testFormContentViewUsesHotModelAndHotClick(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');
        $view = $generator->viewContent('post.create', ['title', 'content']);

        self::assertStringContainsString('hot:model="title"', $view);
        self::assertStringContainsString('hot:model="content"', $view);
        self::assertStringContainsString('hot:click="save"', $view);
        self::assertStringContainsString('<?= $component->title ?>', $view);
    }

    public function testGeneratedClassMatchesExactExpectedSource(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');
        $expected = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\Components\Post;

use Components\Hotfire\Component;

/**
 * Reactive Create component (generated by make:hotfire).
 */
final class Create extends Component
{
    /** Rendered by Hotfire from this exact template (Hotfire view prefix). */
    protected string $view = 'components/hotfire/post/🔥create/create.view';

    public string $title = '';

    public string $content = '';

    /**
     * Action bound from the template via hot:click="save". Add your own
     * persistence/validation logic here.
     */
    public function save(): void
    {
    }
}
PHP;

        // Final newline like a written file.
        $expected .= "\n";

        self::assertSame($expected, $generator->classContent('post.create', ['title', 'content']));
    }

    public function testAllStubTemplatesShipWithThePackage(): void
    {
        $templatesDir = __DIR__.'/../src/Components/Hotfire/templates';

        foreach (['component_class', 'component_action_save', 'component_view', 'component_view_plain', 'component_view_field', 'component_js', 'component_css', 'component_global_css', 'component_test'] as $stub) {
            self::assertFileExists($templatesDir.'/'.$stub.'.stub', 'Missing scaffold stub '.$stub.'.stub');
        }
    }

    public function testGeneratedTestNamespaceMirrorsClassUnderTests(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');
        $test = $generator->testContent('post.create');

        self::assertStringContainsString('namespace Tests\\Components\\Post;', $test);
        self::assertStringContainsString('use App\\Components\\Post\\Create;', $test);
        self::assertStringContainsString('final class CreateTest extends CIUnitTestCase', $test);
        self::assertStringContainsString("Snapshot::encode(['class' => Create::class", $test);
    }

    public function testAllArtifactsCollocateInComponentFolder(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');

        $folder = '/views/components/hotfire/post/🔥create';

        self::assertSame($folder.'/create.php', $generator->classPath('post.create'));
        self::assertSame($folder.'/create.view.php', $generator->viewPath('post.create'));
        self::assertSame($folder.'/create.js', $generator->sidecarPath('post.create', 'js'));
        self::assertSame($folder.'/create.css', $generator->sidecarPath('post.create', 'css'));
        self::assertSame($folder.'/create.global.css', $generator->sidecarPath('post.create', 'global.css'));
        self::assertSame($folder.'/create.test.php', $generator->testPath('post.create'));
    }

    public function testCustomNamespaceOnlyChangesDeclaration(): void
    {
        $generator = new ComponentGenerator('/views', 'Domain\\Posts', '', '🔥');

        self::assertSame('Domain\\Posts\\Post', $generator->classNamespace('post.create'));
        self::assertSame(
            '/views/components/hotfire/post/🔥create/create.php',
            $generator->classPath('post.create'),
        );
    }

    public function testRejectsTraversalAndGarbageNames(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');

        foreach (['', '..', 'a/../b', 'a b'] as $bad) {
            try {
                $generator->segments($bad);
                self::fail('Expected InvalidArgumentException for ['.$bad.'].');
            } catch (InvalidArgumentException) {
                self::assertTrue(true);
            }
        }

        // Repeated separators collapse harmlessly.
        self::assertSame(
            $generator->viewRelative('post//create'),
            $generator->viewRelative('post.create'),
        );

        try {
            $generator = new ComponentGenerator('/views', 'App\\Components', '', '🔥/');
            self::fail('Expected InvalidArgumentException for unsafe emoji.');
        } catch (InvalidArgumentException) {
            self::assertTrue(true);
        }
    }

    public function testPropsRejectsNonIdentifiers(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');

        self::assertSame(['title', 'content'], $generator->props(' title , content '));

        try {
            $generator->props('title, bad-name');
            self::fail('Expected InvalidArgumentException.');
        } catch (InvalidArgumentException) {
            self::assertTrue(true);
        }
    }

    public function testPropsRejectsReservedNames(): void
    {
        $generator = new ComponentGenerator('/views', 'App\\Components');

        foreach (['view', 'component'] as $reserved) {
            try {
                $generator->props($reserved);
                self::fail('Expected InvalidArgumentException for reserved property '.$reserved);
            } catch (InvalidArgumentException) {
                self::assertTrue(true);
            }
        }
    }
}